spring:
  datasource:
    username: root
    password: dsrm
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/TEST
  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      name: admin
      password: dsrm